POST http://localhost:80/api/item
Content-Type: application/json

{}

###
###
GET http://localhost:80/api/camel/sample
Accept: application/json


### istio ingress-gateway를 통한 외부 네트워크 통신 확인
GET http://localhost:80/api/backend/sample
#HOST: devops.example.com
Accept: application/json

###
GET http://localhost:80/api/code-repo-tool-manager/sample
HOST: devops.example.com
Accept: application/json

###
GET http://localhost:80/api/build-tool-manager/sample
HOST: devops.example.com
Accept: application/json

### camel rest 동작 확인
GET http://localhost:7777/api/camel/hello-world
Accept: application/json

### Rest Controller 동작 확인
GET http://localhost:7777/api/build-tool-manager/sample
Accept: application/json

### Rest Controller 동작 확인
GET http://localhost:7777/api/build-tool-manager/sample
Accept: application/json

### build-tool 데이터 하나 만들기
GET http://localhost:7777/api/build-tool-manager/jpa-test
Accept: application/json

### 모든 툴 정보 삭제
DELETE http://localhost:7777/api/build-tool-manager/tools
Accept: application/json

### 모든 툴 정보 조회
GET http://localhost:7777/api/build-tool-manager/tools
Accept: application/json



###

#POST http://localhost:8080/api/camel/create-project
#DELETE http://localhost:7777/api/build-tool-manager/delete-repo
#POST http://localhost:7777/api/camel/projects
POST http://localhost:7777/api/camel/projects-with-fail
#POST http://localhost:8083/api/code-repo-tool-manager/create-repo
#POST http://localhost:8080/api/camel/projects
#POST http://localhost:8081/orders
Content-Type: application/json

{
  "project": {
    "name": "myProject"
  },
  "codeRepoTool": {
    "use": true,
    "type": "GITHUB",
    "name": "myGITHUB",
    "url": "http://github.com/myGITHUB"
  },
  "imageRepoTool": {
    "use": true,
    "type": "REDII",
    "name": "myREDII",
    "url": "http://redii.net/myREDII"
  },
  "buildTool": {
    "use": true,
    "type": "JENKINS",
    "name": "myJENKINS",
    "url": "http://jenkins.com/myJENKINS"
  },
  "otherTool": {
    "use": false,
    "type": null,
    "name": null,
    "url": null
  }
}
###
