GET http://localhost:8080/api/build-tool-manager/jpa-test
Accept: application/json

###
GET http://localhost:8080/api/code-repo-tool-manager/jpa-test
Accept: application/json

###
GET http://localhost:8080/api/image-repo-tool-manager/jpa-test
Accept: application/json

###

