server:
#  port: 8080
#  servlet:
#    context-path: /api/camel

spring:
  application.name: camel
  main.banner-mode: off

logging:
  level:
    com.sds.devops: DEBUG

camel:
#  springboot.main-run-controller: true
#  service:
#    lra:
#      enabled: true
#      coordinator-url: http://localhost:8080
#      local-participant-url: http://localhost:8080/api
#  component:
#    servlet:
#      mapping:
#        enabled: true
#        context-path: /api/camel/*
#        servlet-name: CamelServlet
#        context-path: /camel/*
#  rest:
#    component: undertow
#    port: 8081
#    binding-mode: json_xml
#    binding-mode: json
#    data-format-property.prettyPrint: "true"
#    producer-component: "http4"