server:
  port: 8080
  servlet:
    context-path: /api/camel

spring:
  application.name: camel
  main.banner-mode: off

camel.springboot.main-run-controller: true

camel:
  service:
    lra:
      enabled: true
      coordinator-url: http://localhost:8080
      local-participant-url: http://localhost:8080/api
  component:
    servlet:
      mapping:
        context-path: /api/*