apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: "jwt-example"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  jwtRules:
  - issuer: "testing@secure.istio.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.11/security/tools/jwt/samples/jwks.json"
---
#apiVersion: security.istio.io/v1beta1
#kind: AuthorizationPolicy
#metadata:
#  name: policy1
#  namespace: istio-system
#spec:
#  selector:
#    matchLabels:
#      app: istio-ingressgateway
#  action: DENY
#  rules:
#    - from:
#        - source:
#            notRequestPrincipals: ["*"]
#---
#apiVersion: security.istio.io/v1beta1
#kind: AuthorizationPolicy
#metadata:
#  name: policy2
#  namespace: istio-system
#spec:
#  selector:
#    matchLabels:
#      app: istio-ingressgateway
#  action: ALLOW
#  rules:
#    - to:
#        - operation:
#            paths: ["/keycloak"]



## 3473847939a574146852

## 4e41e1b5be772d6a40d173070bbc66d55602de7b

## https://github.com/login/oauth/authorize

## https://github.com/login/oauth/access_token