apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-tool-manager-v2
spec:
  selector:
    matchLabels:
      app: build-tool-manager
      version: v2
  template:
    metadata:
      labels:
        app: build-tool-manager
        version: v2
    spec:
      containers:
        - name: build-tool-manager
          image: build-tool-manager
          ports:
          - containerPort: 8080
          env:
            - name: spring.datasource.url
              value: jdbc:postgresql://tool-manager-db:5432/tool-manager-db
            - name: spring.datasource.username
              value: userid
            - name: spring.datasource.password
              value: password
            - name: spring.jpa.hibernate.dialect
              value: org.hibernate.dialect.PostgreSQL11Dialect
            - name: spring.jpa.hibernate.ddl-auto
              value: update
            - name: spring.jpa.properties.hibernate.format_sql
              value: "true"
            - name: spring.jpa.show-sql
              value: "true"
            - name: version
              value: "v2"
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 400m
              memory: 300Mi